
export const fullPlaceholderArticles = [
    {
        slug: 'major-political-summit-concludes-with-historic-agreement',
        contentEnglish: 'In a significant development, world leaders gathered at the global summit have officially signed a landmark pact aimed at tackling climate change and reforming international trade policies. The agreement, which came after days of intense negotiations, is being hailed as a monumental step towards a more sustainable and cooperative global future. Key provisions include stricter emissions targets, a multi-billion dollar fund to support developing nations in their green transition, and the removal of several long-standing trade barriers. Analysts believe this could usher in a new era of global diplomacy and economic stability.',
        contentGujarati: 'એક મહત્વપૂર્ણ વિકાસમાં, વૈશ્વિક શિખર સંમેલનમાં ભેગા થયેલા વિશ્વ નેતાઓએ આબોહવા પરિવર્તનનો સામનો કરવા અને આંતરરાષ્ટ્રીય વેપાર નીतिઓમાં સુધારો કરવાના ઉદ્દેશ્યથી એક સીમાચિહ્નરૂપ કરાર પર સત્તાવાર રીતે હસ્તાક્ષર કર્યા છે. કેટલાય દિવસોની તીવ્ર વાટાઘਾટો પછી આવેલી આ સમજૂતીને વધુ ટકાઉ અને સહકારી વૈશ્વिक ભવિષ્ય તરફના એક સ્મારક પગલા તરીકે બિરદાવવામાં આવી રહી છે. મુખ્ય જોગવાઈઓમાં કડક ઉત્સર્જન લક્ષ્યો, વિકાસશીલ રાષ્ટ્રોને તેમના હરિયાળા સંક્રમણમાં ટેકો આપવા માટેનું બહુ-અબજ ડોલરનું ભંડોળ અને કેટલાય લાંબા સમયથી ચાલતા વેપાર અવરોધોને દૂર કરવાનો સમાવેશ થાય છે. વિશ્લેષકો માને છે કે આ વૈશ્વિક કૂટનીતિ અને આર્થિક સ્થિરતાના નવા યુગની શરૂઆત કરી શકે છે.',
    },
    {
        slug: 'tech-giant-unveils-revolutionary-ai-chip',
        contentEnglish: 'The technology world is buzzing with the announcement of the "QuantumCore" AI chip. Developed in secrecy over five years, the chip utilizes novel quantum-inspired architecture to achieve processing speeds previously thought to be theoretical. During a live demonstration, the chip outperformed the leading supercomputer in a complex protein-folding simulation by a factor of over 1000. The company stated that QuantumCore will initially be available to research institutions to accelerate scientific discovery, with a consumer-grade version planned for release within the next three years, potentially revolutionizing everything from personal computing to autonomous vehicles.',
        contentGujarati: 'ટેકનોલોજીની દુનિયા "ક્વોન્ટમકોર" AI ચિપની જાહેરાતથી ગુંજી રહી છે. પાંચ વર્ષથી ગુપ્ત રીતે વિકસાવવામાં આવેલી આ ચિપ, પ્રوسેસિંગ ગતિ પ્રાપ્ત કરવા માટે નવલકથા ક્વોન્ટમ-પ્રેરિત आર્કિટેક્ચરનો ઉપયોગ કરે છે જે અગાઉ સૈદ્ધાંતિક માનવામાં આવતી હતી. જીવંત પ્રદર્શન દરમિયાન, ચિપે એક જટિલ પ્રોટીન-ફોल्डિંગ સિમ્યુલેશનમાં અગ્રણી સુપર કોમ્પ્યુટરને 1000 થી વધુના પરિબળથી પાછળ છોડી દીધું. કંપનીએ જણાવ્યું હતું કે ક્વોન્ટમકોર શરૂઆતમાં વૈજ્ઞાનિક શોધને વેગ આપવા માટે સંશોધન સંસ્થાઓ માટે ઉપલબ્ધ થશે, આગામી ત્રણ વર્ષમાં ઉપભੋક્તા-ગ્રેડ સંસ્કરણ બહાર પાડવાની યોજના છે, જે પર્સનल કમ્પ્યુટિંગથી લઈને સ્વાયત્ત વાહનો સુધીની દરેક બાબતમાં ક્રાંતિ લાવી શકે છે.',
    },
    {
        slug: 'national-cricket-team-wins-world-championship',
        contentEnglish: 'The nation erupted in celebration tonight as the national cricket team clinched the World Championship title in a nail-biting final against their fiercest rivals. Chasing a formidable target of 288, the team found themselves needing 15 runs off the final over. It all came down to the last ball, with 4 runs required to win. The star batsman, previously struggling for form, smashed a towering six over long-on, sealing a historic victory and ending a 12-year drought for the coveted trophy. Fireworks lit up the sky in major cities as fans poured into the streets to celebrate the dramatic win.',
        contentGujarati: 'આજે રાત્રે રાષ્ટ્રીય ક્રિકેટ ટીમે તેમના સૌથી કટ્टर હરીફો સામેની રોમાંચક ફાઇનલમાં વર્લ્ડ ચેમ્પियनશિપનો ખિતાબ જીતી લેતા સમગ્ર દેશ ઉજવણીમાં ડૂબી ગયો હતો. 288 ના મુશ્કેલ લક્ષ્યનો પીછો કરતા, ટીમને અંતિમ ઓવરમાં 15 રનની જરૂર હતી. બધું છેલ્લા બોલ પર આવી ગયું, જેમાં જીતવા માટે 4 રનની જરૂર હતી. અગાઉ ફોર્મ માટે સંઘर्ष કરી રહેલા સ્ટાર બેટ્સમેને લોંગ-ઓન પર એક ઊંચો છગ્ગો ફટકારીને ઐતિહાસિક વિજય સુનિશ્ચિત કર્યો અને પ્રતિષ્ઠિત ટ્રોફી માટેના 12 વર્ષના દુકાળનો અંત આણ્યો. નાટકીય જીતની ઉજવણી કરવા માટે ચાહકો શેરીઓમાં ઉમटी પડતાં મુખ્ય શહેરોમાં આકાશ આતશબાજીથી ઝળહળી ઉઠ્યું હતું.',
    },
    {
        slug: 'archaeologists-uncover-lost-city-in-dense-jungle',
        contentEnglish: 'A team of international archaeologists has made a groundbreaking discovery deep within the Amazon rainforest, uncovering the ruins of a sprawling ancient city. Using advanced LiDAR technology to map the terrain beneath the dense jungle canopy, the team identified a vast network of pyramids, plazas, and residential complexes connected by a sophisticated system of causeways. Initial estimates suggest the city was inhabited from 500 BC to 1000 AD and may have supported a population of over 100,000 people. "This changes everything we thought we knew about pre-Columbian civilizations in this region," stated the lead archaeologist. "We are looking at a highly organized, urban society that thrived in the heart of the jungle for centuries."',
        contentGujarati: 'આંતરરાષ્ટ્રીય પુરાતत्वविદોની એક ટીમે એમેઝોન वर्षावनની ઊંડાઈમાં एक अभूतपूर्व શોધ કરી છે, જેમાં એક વિસ્તൃത પ્રાચીન શહેરના ખંડેરોનો પર્દાફાશ થયો છે. ગાઢ જંગલની છتری નીચે ભૂપ્રદેશનો નકશો બનાવવા માટે અદ્યતન LiDAR ટેકનોલોજીનો ઉપયોગ કરીને, ટીમે પિરાमिડો, પ્લાઝાઓ અને રહેણાંક સંकुલોના विशाल નેટવર્કને ઓળખી કાઢ્યું જે કોઝવેની એક అధునాతన પ્રણાલી ద్వారా જોડાયેલું હતું. પ્રારંભિક અંદાજો સૂચવે છે કે આ શહેર 500 BC થી 1000 AD સુધી વસવાટ કરતું હતું અને 100,000 થી વધુ લોકોની વસ્તીને ટેકો આપી શક્યું હોત. "આ આ પ્રદેશમાં પૂર્વ-કોલમ્બિયન સંસ્કૃતિઓ વિશે આપણે જે વિચાર્યું હતું તે બધું બદલી નાખે છે," મુખ્ય પુરાતત્વविદે જણાવ્યું. "અમે એક અત્યંત સંગઠित, શહેરી સમાજને જોઈ રહ્યા છીએ જે સદીઓથી જંગલના હૃદયમાં વિકસ્યો હતો."',
    },
    {
        slug: 'local-food-festival-celebrates-cultural-diversity',
        contentEnglish: 'The annual City Food Festival drew record crowds over the weekend, transforming the downtown park into a global culinary village. Over 150 vendors representing more than 50 countries offered a dizzying array of dishes, from spicy Thai curries to savory Argentine empanadas. The event not only provided a feast for the senses but also a platform for cultural exchange, with traditional music and dance performances taking place throughout the day. "Food is a universal language," said the event organizer. "It brings people together and helps us celebrate the beautiful mosaic of cultures that makes our city so special."',
        contentGujarati: 'વાર્ષિક સિટી ફૂડ ફેસ્ટિવલે સપ્તાહના અંતે રેકોર્ડ ભીડ ખેંચੀ, ડાઉનટાઉન પાર્કને વૈશ્વिक पाक ગામમાં ફેરવી દીધું. 50 થી વધુ દેશોનું પ્રતિનિધિત્વ કરતા 150 થી વધુ વિક્રેતાઓએ મસાલેदार થાઈ કરીથી લઈને સ્વાદિષ્ટ આર્જેન્ટિનાના એમ્पानाडा સુધીની વાનગીઓની એક ચક્કર લગાવणारी શ્રેણી ઓફર કરી. આ કાર્યક્રમે માત્ર ઇન્દ્રિયો માટે જ તહેવાર પૂરો પાડ્યો ન હતો, પરંતુ સાંસ્કૃતિક આदानप्रदान માટેનું एक મંચ પણ પૂરું પાડ્યું હતું, જેમાં દિવસભર પરંપરાगत સંગીत અને નૃત્ય પ્રదర్శનો યોજાયા હતા. "ખોરાક એક સાર્વત્રિક ભાષા છે," ઇવેન્ટ આયોજકે કહ્યું. "તે લોકોને એકસાથે લાવે છે અને આપણને તે સુંદર સાંસ્કૃતિક મોઝેકની ઉજવણી કરવામાં મદદ કરે છે જે આપણા શહેરને इतना खास બનાવે છે."',
    }
];
